version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Devfile
      args:
        SITE_LEVEL: "development"
    ports:
     - "8081:80"
     - "3308:3306"
    volumes:
      - .:/var/www/html
    environment:
        PHP_XDEBUG_REMOTE_HOST: "192.168.66.1"
        PHP_IDE_CONFIG: "serverName=dev.local"
        SITE_ENV: "production"
    extra_hosts:
        # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:192.168.40.204"