version: '3'

services:
  web:
    build: .
    ports:
      - "8082:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    ports:
     - "4407:3306"
    volumes:
     - /var/lib/mysql
    environment:
     MYSQL_DATABASE: mydb
     MYSQL_USER: user
     MYSQL_PASSWORD: test
     MYSQL_ROOT_PASSWORD: test